language: C
sudo: required
dist: trusty

addons:
  sonarqube: true

env:
  global:
    secure: SyaNVOjrqmBAsW0Cq7qpxUjbKSnKoEebf645m0TB+RTU5bqdZfgLgSheyKFb4rDpTjMv2yp3MgdPQA5tid5uZoH4KzyTvO3rckH+F3X2cBlIWbn9L5cOYO5j6+sxL7YtbAyxDknmEfjFRP3cX1VOu5zX5+qtSDgHjB3LZqBBfUgpFZhtwsq7HT5DiAIZ43xqQM0fdpg4DUV85f+BRZvDZtKTeKBiTEemTmb9U7wE0sKdMA/6oS3hQWrs+7/SmnpryesyJ1rs3XKLy2tOPv5nwdNxezcG3IBdnq6TQnk4nL07YNqelfO01MTHkjyE70AircX3eRvtlsa4QDxbP8wqxAL+sK2w9gpm+lZuSPgIaMw0doLeLvzK0JQc2Y9SYzLs72OQOKeuVUUVfE3J4CznRTwLEjjmPR3ZY8owANyYkvs8J2WiWSGFlEjzlRDOEr12NJGy2Mc1d05M8F5d0cnA/KR+GLhueh3DcqYLmmoGyuSYHB9zYfQRBVaMazY6GKG0MWrZ9mGNDwa/YXOQHXtXQeqnzGng1VWU9QvFBDRpF+bJvOnIwcvbJJk+mrsNRi7kuVkmsGiXuCpZPmv8vo9/+hIk21/XPqA9CeDvxKzQT2p5poAtohO/USrdmFmex9uwLikJV9Jguc4gfLeEH2bzrmtk1+cxGS558xPF4BOTJS0=

script:
- sonar-scanner -e -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
