language: C
sudo: required
dist: trusty
addons:
  sonarqube: true
env:
  global:
    secure: SyaNVOjrqmBAsW0Cq7qpxUjbKSnKoEebf645m0TB+RTU5bqdZfgLgSheyKFb4rDpTjMv2yp3MgdPQA5tid5uZoH4KzyTvO3rckH+F3X2cBlIWbn9L5cOYO5j6+sxL7YtbAyxDknmEfjFRP3cX1VOu5zX5+qtSDgHjB3LZqBBfUgpFZhtwsq7HT5DiAIZ43xqQM0fdpg4DUV85f+BRZvDZtKTeKBiTEemTmb9U7wE0sKdMA/6oS3hQWrs+7/SmnpryesyJ1rs3XKLy2tOPv5nwdNxezcG3IBdnq6TQnk4nL07YNqelfO01MTHkjyE70AircX3eRvtlsa4QDxbP8wqxAL+sK2w9gpm+lZuSPgIaMw0doLeLvzK0JQc2Y9SYzLs72OQOKeuVUUVfE3J4CznRTwLEjjmPR3ZY8owANyYkvs8J2WiWSGFlEjzlRDOEr12NJGy2Mc1d05M8F5d0cnA/KR+GLhueh3DcqYLmmoGyuSYHB9zYfQRBVaMazY6GKG0MWrZ9mGNDwa/YXOQHXtXQeqnzGng1VWU9QvFBDRpF+bJvOnIwcvbJJk+mrsNRi7kuVkmsGiXuCpZPmv8vo9/+hIk21/XPqA9CeDvxKzQT2p5poAtohO/USrdmFmex9uwLikJV9Jguc4gfLeEH2bzrmtk1+cxGS558xPF4BOTJS0=
deploy:
  skip_cleanup: true
  provider: launchpad
  slug: "~armadito/armadito-web-ui/+git/main"
  oauth_token:
    secure: Eg1+e36nuAQBjw218GVM8nV4xbbOBoGHlOCkGdOKaUjd46JCmR00BRE2g41IbWGbQPu8JhceMyk1rw/kY16+Pm9lBi5DsJWuqi/Fmapxyg3b3WhLZUmZhZzs4ddDbGC/VHD+eVq27NxagBgsGQcWaAnKAIjrG5Uj0ojtsX+LHGV0guCByh73kuvSHJX28w3zskNIOK8TMY6nx4V/skIT7pfs5lxOxA4jXhcH8Gzu1IO2Cip5muCa5YqEEdIXYMBx1C0O1UPbeV6GGMAScyQQZ9iz5nHkKe2VpbeOahabh3gH2bCaB+DzD2T5/9ED3UrCyAyvaqcPOeco38R95SQh0WXHrxnBZSu1z/lflB+9T9H28y8J5AMJ0S7NFeiE0xAJvVGDSiSdUVQD6euniSwYrXIeErzkHstGDgFzDHMbzxNzNzeztYflp6VHUN53Kz1nSWfV7+3AtJFTiwTN9p88aH1WMcc8mka7ohFiWkz+lzH+B800LeIb5fJ2VDLRhx9rVCMV9fOH+8pTSnxr3hfvmlNgZ9MRwiEFE6YpkBQsuFtH1j+Bv2b/hSLHr2QoparJEu9javCOk8xM6rer2d1Qyb5oMJppFQaStwXMRB7eM9CKi2OqQdVL67muU1uhPtPjbU6FaHjZ9P2yFg1fLqHt6kMZCGBxbzoeaG8BLct5q88=
  oauth_token_secret:
    secure: Zhq/dV28Fx34+2Kej3U5LrM2OxycVmQVPl0tQ8wQV1b+aajU0VxKst+5hfjjPgXWdN2F4h/mzdHimLjf2KiOx5BA7LIJC8AGbFViqM9FbJ3Vj6SxgEriYxeUUEI0lpcNQnhyjS1kGS7ZfVSgkYf1bYn29PB7/y4A5JaA/fI1jK5MWi8/6NyBTrz8BbomgNSxFhQTU1RK1dv51O7hrRuHI80emKlkuiVamJi32L0q4V9rSLbnDrl7iiwctL9tBl06ffJL5ekc+J+bCSIKdOzXtPcl84IeOZCiWeMNUyf/o9No7jhjJPrBZxT8aFaYXJIid4nGJPl3TS8LTZakkXbNNIppWcJzgjowVRzxc6Qeik7KCp+uXrk/zeUUn5+XM7MEeygTQYL2XHVDlxpZYlyTe5a2RgXc7TN+3TM5nyqHb3NGCAWlGXk9syShvGOmkqWGSXP60mtwVWNkasqWRJg3OM8ESbYDT6eT2qQk6Zk6uuDVGzHG5d9d02ql19kT7M2Z2RxzkQOsvTvTJbinBYcmc/aMtt4smo+H8Vnz92Zx0TdI6lamffJRkAPyQ8OAeCvzSZ6ogHpk6y2qo/qa445CQmdufVqduAa/ZDg0YxjwprhWV9ex+Xodiq1fpwSUM25MijRwxyF4h/X/79HQveWBptbevVeeC60n4koq7G7R/Xk=
  on:
    tags: true
script:
- sonar-scanner -e -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
